### ISSUE TITLE
En tant que instructrice, je veux suivre les demandes d'ajout d'ingrédient avec un tableau de bord

### ISSUE THREAD

**Issue by hfroot** [betagouv/complements-alimentaires#1305]
[Maquette 1](https://www.figma.com/design/0pv6zTHf7IW3wbxmmScSUh/Nouvel-ingr%C3%A9dient?node-id=24-26765&node-type=frame&t=g5bXGT25oBUbRGp7-0)
[Maquette 2](https://www.figma.com/design/0pv6zTHf7IW3wbxmmScSUh/Nouvel-ingr%C3%A9dient?node-id=54-9512&node-type=frame&t=gZXSmWpmlHpM7nBO-0)

- [x] Tableau basic #1239 
- [x] Lien depuis le tableau de bord pour les instructrices vers cette page #1239 
- [x] Affichage de statut de demande (nouveau, attente info, refus, remplacé, ajouté dans la BDD...) #1503 
- [x] Triage par date de demande et statut de décla
- [x] Filtrage par type d'ingrédient https://github.com/betagouv/complements-alimentaires/pull/1703
- [x] Lien vers page pour controler l'ingrédient #1338  
- [x] Confirmer quelles demandes à afficher
- [ ] Option pour annuler l'action faite https://github.com/betagouv/complements-alimentaires/issues/1702
