### ISSUE TITLE
En tant que instructrice, je veux prendre une décision sur la demande de l'ajout d'un nouvel ingrédient

### ISSUE THREAD

**Issue by hfroot** [betagouv/complements-alimentaires#1306]
Ce sera possible depuis la page pour afficher les détails de la demande. Il y a plusieurs maquettes, [la première](https://www.figma.com/design/0pv6zTHf7IW3wbxmmScSUh/Nouvel-ingr%C3%A9dient?node-id=13-17906&node-type=frame&t=g5bXGT25oBUbRGp7-0)

- [x] Option pour demander plus d'info #1303 
- [x] Option pour refuser #1303
- [x] Option de créer un nouvel ingrédient #1237 
- [x] Option de retrouver un ingrédient existant et remplacer la demande avec l'ingrédient trouvé https://github.com/betagouv/complements-alimentaires/issues/1320
- [x] #1439
- [ ] Rapprocher le design du titre modal pour les notes à la maquette
- [x] #1502

**Comment by hfroot** [comment]
Si besoin du changement de design pour le modal, on pourrait créer un nouveau issu
