### ISSUE TITLE
Amélioration tooling côté Vue

### ISSUE THREAD

**Issue by ddahan** [betagouv/complements-alimentaires#348]
```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Auto import des composants (fonctionne pour les composants Vue ou externe, mais pas internes)
- [ ] Import sorting
- [ ] Conf ES Lint / Prettier à "accorder" ensemble (par exemple un auto-import ne doit pas ajouter de `;` à la fin d'une ligne)
- [ ] Eviter les erreurs "faux-positif" dans VS Code (par exemple, avoir du code souligné en rouge alors que c'est juste le formatting qui n'est pas bon - ça doit être un warning souligné en jaune, ou mieux, rien du tout puisque l'auto-formatting fait le travail)
- [ ] Prettier Tailwind [class sorting](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)
- [ ] Imports suggestions ne fonctionnent pas parfois
```

**Comment by ddahan** [comment]
> Imports suggestions ne fonctionnent pas parfois

<img width="706" alt="image" src="https://github.com/betagouv/complements-alimentaires/assets/1933516/e7482c9e-4c64-47a7-8fa7-5004288a84b2">
