### ISSUE TITLE
Petites améliorations accessibilités

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#629]
## TODO

- [ ] Ajouter un lien d'[évitement](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/lien-d-evitement/) sur la page d'accueil
- [ ] Le titre de la page Recherche doit être spécifique (et pas juste "Compl'Alim")
- [ ] les champs de formulaire (page Recherche et page Nouvelle Déclaration) doivent avoir un placeholder qui facilite la compréhension
- [ ] dans la page nouvelle déclaration ajouter un texte pour dire que l'asterix est un champ requis
- [ ] dans la page nouvelle déclaration expliciter les formats spécifiques (dose journalière recomandée)

![Image](https://github.com/betagouv/complements-alimentaires/assets/1618987/eebe3b1e-0dd0-466c-a0dc-cfb23bf3713c)

image issue du doc [easy check accessibilité](https://docs.google.com/spreadsheets/d/1jIj52Nv6qN3vNWhalhr05J0IIsx7Q2vL9BtPqEdJvlI/edit?pli=1&gid=340274770#gid=340274770)
