### ISSUE TITLE
Déduplications déjà validées

### ISSUE THREAD

**Issue by pletelli** [betagouv/complements-alimentaires#671]
```[tasklist]
### Tasks
- [ ] trouver le mécanisme pour le nettoage (à l'import ? un trigger de la base ? un mécanisme django ?)
- [x] on ne garde que la substance si elle a un n° CAS
- [x] on ne garde que la substance lorsque la substance est métabolite de plante
- [x] les ingredients qui se terminent en -ase sont des substances
- [x] on ne garde que les substances qui se terminent par -ose
- [x] on ne garde que les substance qui se terminent par -ate
- [x] on ne garde que les substances qui commencent par -acide
- [x] on ne garde que les ingrédients qui commencent par huile, lait, miel
- [x] on supprime les subst et ingredients qui sont des micro-organismes
- [ ] conserver tous les champs des ingrédients devenus obsolètes
- [ ] ajout de types de substances (enzymes, vitamines, minéraux, acide aminés, acide gras, métabolite)
```
Références ici https://www.notion.so/betagouv-dinum/Atelier-sur-les-substances-ingr-dients-f03cae1a1c334bd0bd68cc40fd729322

+ un validateur de données ? (validata)

**Comment by pletelli** [comment]
Cette tâche me permet de documenter un peu notre stack data actuelle 


![Image](https://github.com/user-attachments/assets/7f52cc64-b49f-4e45-8751-e53286e94505)
